name: aakrikada
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0-196.1.beta

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  flutter_otp_text_field: ^1.5.1+1
  flutter_riverpod: ^2.6.1
  geocoding: ^4.0.0
  image_picker: ^1.1.2
  intl: any
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.4
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family:  Roboto
      fonts:
        - asset: assets/fonts/roboto.ttf
